---
title: "lynch predictions"
author: "Iwan"
date: "2024-04-09"
output: html_document
---

```{r setup, include=FALSE}
library(coda4microbiome)
library(tidyverse)
library(codacore)
```


```{r ranko function}
#### Ranko's geweldige filter functie -----
#================================================================================
  # function for filtering microbiome (metaphlan) results
  # - takes dataframe (any)
  # - replaces NAs with 0.0
  # - filters OUT taxa present in less then presPerc samples
  # - filters OUT taxa with mean releative abundance < minMRelAb
  # - filters OUT taxa with median relative abundance < minMedRelAb
  # - filters OUT taxonomic levels not in keepLevels ()
  #   -> keepLevels should be vector of following: T = strain, S = species, G = Genera, F = families
  #                                                O = Orders, C = classes, P = phyla, K = Kingdoms
  #   -> example: keepLevels=c('S','G') keeps only species and genera
  # - filters OUT domains not in keepDomains: 
#   -> input is vector of following: Eukaryota, Bacteria, Viruses, Archaea
#   -> example: keepDomains=c('B') keeps only bacteria, removes viruses, archaea and eukarya
# - if rescaleTaxa = True, rescales relative abundancies after filtering
# returns modified dataframe
# NOTES:
# - assumes metaphlan encoding (k__<kingdom>.o__<order> ... ); it will mess stuff
# up if non-metagenome rows are encoded like this!
# DEFAULTS: 
# - removes non-bacteria
# - keeps all except kingdoms
filterMetaGenomeDF <- function(inDF,presPerc = 0.1,minMRelAb = 0.01,minMedRelAb=0.0,
                               rescaleTaxa=T,verbose=T,
                               keepDomains=c('Bacteria','Archaea'),
                               keepLevels=c('S','G','F','O','C','P'),
                               keepUnknown=F) {
  
  # -- drop unknown & rescale? --
  if (!keepUnknown) {
    inDF$UNKNOWN <- NULL
  }
  tCols = grep('k__',colnames(inDF)) # colums with microbiome
  tColsNMG = grep('k__',colnames(inDF),invert = T) # colums with microbiome
  # replaces NAs in microbiome with 0s
  for (c in tCols) {
    inDF[,c][is.na(inDF[,c])] <- 0.0
  }
  
  # filter for presence
  # -----------------
  nrRemoved = 0
  toRemove = c()
  for (c in tCols) {
    nrnZ = as.numeric(sum(inDF[,c]!=0.0))
    if ( (nrnZ/as.numeric(nrow(inDF))) < presPerc) {
      # if (verbose) {
      #   print (paste('col',c,': ',colnames(inDF)[c],'; nr non Zero:',nrnZ,'=',nrnZ/as.numeric(nrow(inDF)),'>> Column removed!'))
      # }
      nrRemoved = nrRemoved + 1
      toRemove <- c(toRemove,c)
    }
  }
  if (length(toRemove) > 0) {
    inDF <- inDF[,-toRemove]
  }
  tCols = grep('^[dgtspcfko]__',colnames(inDF)) # colums with microbiome
  if (verbose) {print (paste(' > presence filter: Removed',nrRemoved,'taxa!, ',length(tCols),'taxa left!')); }
  
  # filter for abundance (mean)
  # ---------------------------
  nrRemoved = 0
  toRemove = c()
  for (c in tCols) {
    mn = mean(inDF[,c])
    if ( mn < minMRelAb) {
      #if (verbose) {
      #  print (paste('col',c,': ',colnames(inDF)[c],'; mean rel abundance:',mn,' >> Column removed!'))
      #}
      nrRemoved = nrRemoved + 1
      toRemove <- c(toRemove,c)
    }
  }
  if (length(toRemove) > 0) {
    inDF <- inDF[,-toRemove]
  }
  tCols = grep('k__',colnames(inDF)) # colums with microbiome
  if (verbose) {print (paste(' > mean abundance filter: Removed',nrRemoved,'taxa!, ',length(tCols),'taxa left!')); }
  
  # filter for abundance (median)
  # -----------------------------
  nrRemoved = 0
  toRemove = c()
  for (c in tCols) {
    mn = median(inDF[,c])
    if ( mn < minMedRelAb) {
      #if (verbose) {
      #  print (paste('col',c,': ',colnames(inDF)[c],'; median rel abundance:',mn,' >> Column removed!'))
      #}
      nrRemoved = nrRemoved + 1
      toRemove <- c(toRemove,c)
    }
  }
  if (length(toRemove) > 0) {
    inDF <- inDF[,-toRemove]
  }
  if (verbose) {print (paste(' > median abundance filter: Removed',nrRemoved,'taxa!, ',length(tCols),'taxa left!')); }  
  
  # keep domains
  # -----------------------------
  toKeep <- NULL
  if (length(keepDomains) == 1) {
    if (keepDomains == 'All' | keepDomains == "") {
      toKeep = grep('k__',colnames(inDF),invert = T)
    } else {
      toKeep = grep(paste('k__',d,sep=''),colnames(inDF))
    }
  } else {
    for (d in keepDomains) {
      #d print(d)
      toKeep = c(toKeep,grep(paste('k__',d,sep=''),colnames(inDF)))
    }
  }
  inDF <- inDF[,toKeep]
  taxaP <- c()
  taxaP <- as.data.frame(taxaP)
  taxaC <- c()
  taxaC <- as.data.frame(taxaC)
  taxaO <- c()
  taxaO <- as.data.frame(taxaO)
  taxaK <- c()
  taxaK <- as.data.frame(taxaK)
  taxaF <- c()
  taxaF <- as.data.frame(taxaF)
  taxaG <- c()
  taxaG <- as.data.frame(taxaG)
  taxaS <- c()
  taxaS <- as.data.frame(taxaS)
  taxaT <- c()
  taxaT <- as.data.frame(taxaT)
    # remove taxonomic levels
  # -----------------------------
  inDFnonTaxa <- as.data.frame(inDF[,grep('k__',colnames(inDF),invert=T)])
  colnames(inDFnonTaxa) <- colnames(inDF)[grep('k__',colnames(inDF),invert=T)]
  
  inDF2 <- as.data.frame(inDF[,grep('k__',colnames(inDF),invert=F)])
  # pick strains (T)
  taxaTCols <- grep('t__',colnames(inDF2))
  taxaT <- as.data.frame(inDF2[,taxaTCols])
  colnames(taxaT) <- colnames(inDF2)[grep('t__',colnames(inDF2))]
  if (length(taxaTCols) > 0) {inDF2 <- inDF2[,-taxaTCols]}
  # pick species (S)
  taxaSCols <- grep('s__',colnames(inDF2))
  if (length(taxaSCols) > 0) {
    taxaS <- as.data.frame(inDF2[,taxaSCols])
    colnames(taxaS) <- colnames(inDF2)[grep('s__',colnames(inDF2))]
  }
  if (length(taxaSCols) > 0) {inDF2 <- inDF2[,-taxaSCols]}
  # pick genera (G)
  taxaGCols <- grep('g__',colnames(inDF2))
  if (length(taxaGCols) > 0) {
    taxaG <- as.data.frame(inDF2[,taxaGCols])
    colnames(taxaG) <- colnames(inDF2)[grep('g__',colnames(inDF2))]
  }
  if (length(taxaGCols) > 0) {inDF2 <- inDF2[,-taxaGCols]}
  # pick families (F)
  taxaFCols <- grep('f__',colnames(inDF2))
  if (length(taxaFCols) > 0) {    
    taxaF <- as.data.frame(inDF2[,taxaFCols])
    colnames(taxaF) <- colnames(inDF2)[grep('f__',colnames(inDF2))]
  }
  if (length(taxaFCols) > 0) {inDF2 <- inDF2[,-taxaFCols]}
  # pick orders (O)
  taxaOCols <- grep('o__',colnames(inDF2))
  if (length(taxaOCols) > 0) {
    taxaO <- as.data.frame(inDF2[,taxaOCols])
    colnames(taxaO) <- colnames(inDF2)[grep('o__',colnames(inDF2))]
  }
  if (length(taxaOCols) > 0) {inDF2 <- inDF2[,-taxaOCols]}
  # pick classes (C)
  taxaCCols <- grep('c__',colnames(inDF2))
  if (length(taxaCCols) > 0) {
    taxaC <- as.data.frame(inDF2[,taxaCCols])
    colnames(taxaC) <- colnames(inDF2)[grep('c__',colnames(inDF2))]
  }
  if (length(taxaCCols) > 0) {
    if( length(colnames(inDF2)) - length(taxaCCols) == 1) {
      ccn <- colnames(inDF2)[grep('c__',colnames(inDF2))]
      tempN <- colnames(inDF2)[!(colnames(inDF2) %in% ccn)]
      inDF2 <- as.data.frame(inDF2[,-taxaCCols])
      colnames(inDF2) <- tempN
    } else {
      inDF2 <- inDF2[,-taxaCCols]
    }
  }
  # pick phyla (P)
  taxaPColsKeepN <- NULL
  taxaPCols <- grep('p__',colnames(inDF2))
  if (length(taxaPCols) > 0) {
    taxaPColsN <- colnames(inDF2)[grep('p__',colnames(inDF2))]
    taxaPColsKeep <- grep('p__',colnames(inDF2),invert = T)
    taxaPColsKeepN <- colnames(inDF2)[grep('p__',colnames(inDF2),invert = T)]
    taxaP <- as.data.frame(inDF2[,taxaPCols])
    colnames(taxaP) <- taxaPColsN
  }
  # pick kingdoms (K)
  if (length(taxaPCols) > 0) {inDF2 <- as.data.frame(inDF2[,taxaPColsKeep])}
  if (!is.null(taxaPColsKeepN)){
    colnames(inDF2) <- taxaPColsKeepN
  }
  taxaK <- inDF2
  # pick 
  oDF <- inDFnonTaxa
  if (verbose) {print ('Keeping following taxonomic levels:'); print(keepLevels)}
  if (ncol(taxaK) > 0) {  
    if ('K' %in% keepLevels) {
      if (verbose){print(paste(' -> kept',ncol(taxaK),'Kingdoms'))}
      if (rescaleTaxa) {taxaK <- taxaK/rowSums(taxaK)}
      oDF <- cbind(oDF,taxaK)}
  }
  if (ncol(taxaP) > 0) {
    if ('P' %in% keepLevels) {
      if (verbose){print(paste(' -> kept',ncol(taxaP),'Phyla'))} 
      if (rescaleTaxa) {taxaP <- taxaP/rowSums(taxaP)}
      oDF <- cbind(oDF,taxaP)}
  }
  if (ncol(taxaC) > 0) {
    if ('C' %in% keepLevels) {
      if (verbose) {print(paste(' -> kept',ncol(taxaC),'Classes'))} 
      if (rescaleTaxa) {taxaC <- taxaC/rowSums(taxaC)}
      oDF <- cbind(oDF,taxaC)}
  }
  if (ncol(taxaO) > 0) {
    if ('O' %in% keepLevels) {
      if (verbose){print(paste(' -> kept',ncol(taxaO),'Orders'))}
      if (rescaleTaxa) {taxaO <- taxaO/rowSums(taxaO)}
      oDF <- cbind(oDF,taxaO)}
  }
  if (ncol(taxaF) > 0) {
    if ('F' %in% keepLevels) {
      if (verbose){print(paste(' -> kept',ncol(taxaF),'Families'))}
      if (rescaleTaxa) {taxaF <- taxaF/rowSums(taxaF)}
      oDF <- cbind(oDF,taxaF)}
  }
  if (ncol(taxaG) > 0) { 
    if ('G' %in% keepLevels) {if (verbose){ print(paste(' -> kept',ncol(taxaG),'Genera'))}
      if (rescaleTaxa) {taxaG <- taxaG/rowSums(taxaG)}
      oDF <- cbind(oDF,taxaG)}
  }
  if (ncol(taxaS) > 0) {
    if ('S' %in% keepLevels) {if (verbose){print(paste(' -> kept',ncol(taxaS),'Species'))}
      if (rescaleTaxa) {taxaS <- taxaS/rowSums(taxaS)}
      oDF <- cbind(oDF,taxaS)}
  }
  if (ncol(taxaT) > 0) {
    if ('T' %in% keepLevels) {if (verbose){print(paste(' -> kept',ncol(taxaT),'Strains'))}
      if (rescaleTaxa) {taxaT <- taxaT/rowSums(taxaT)}
      oDF <- cbind(oDF,taxaT)}
  }
  if (verbose) {print ('data processing done, returning Dataframe')}
  oDF
}
```


```{r preprocessing}

lynch_metadata <- read.csv('/Users/iwan/Research/Lynch_predictions/metadata/meta_Lynch.csv')

lynch_species <- read.delim2('/Users/iwan/Research/Lynch_predictions/metadata/species_filtered_Lynch.csv', sep =',')


rownames(lynch_species) <-  lynch_species$X

lynch_species$X <- NULL
#new_names <- c()
#for (i in colnames(lynch_species)){
#  new_names <- c(new_names, paste(str_split(i, '_')[[1]][1:3], collapse = '_'))
#}
#colnames(lynch_species) <- new_names



#lynch_species <- as.data.frame(t(lynch_species))


#filter

#saved_rownames <- rownames(lynch_species)
#lynch_species$X <- NULL

#lynch_species <- mutate_all(lynch_species, function(x) as.numeric(as.character(x)))


#Taxa_DR_species <- filterMetaGenomeDF(lynch_species, presPerc = 0.20,minMRelAb = 0.01 ,minMedRelAb=0.0,
 #                                     rescaleTaxa=T,verbose=T,
#                                      keepDomains=c('Bacteria','Archaea'),
 #                                     keepLevels=c('S'),
#                                      keepUnknown=F) 


#updated_rownames <- str_split_i(saved_rownames, '_', 1)
#row.names(Taxa_DR_species) <- saved_rownames
#Taxa_DR_species <- na.omit(Taxa_DR_species)

shortnames <- c()
for (i in colnames(lynch_species)){
  shortnames <- c(shortnames, paste('s__' ,str_split_i(i, '__',8)))
}
#shortnames[1] <- 'X'
colnames(lynch_species) <- shortnames

lynch_species <- mutate_all(lynch_species, function(x) as.numeric(as.character(x)))


lynch_species[lynch_species == 0] <- NA
lynch_species[sapply(lynch_species, is.numeric)] <- lapply(lynch_species[sapply(lynch_species, is.numeric)], function(a) ifelse(is.na(a), min(a, na.rm = TRUE)/2, a))

#rownames(lych_metadata) <- lych_metadata$X
#lych_metadata$X <- NULL

lynch_df <- merge(lynch_species, lynch_metadata, by.x = 0, by.y = 'X')
rownames(lynch_df) <- lynch_df$Row.names
lynch_df$Row.names <- NULL



```



```{r predicting presence of lesions}




library(coda4microbiome)



current_df <- lynch_df[!is.na(lynch_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`),]
current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`[current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`==0] = 'No'
current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`[current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`==1] = 'Yes'

x <- current_df[,1:244]
y <- current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




my.sum <- 0
for (i in 1:length(coda_glmnet_Crohn$taxa.name)){
  current <- log(current_df[, coda_glmnet_Crohn$taxa.name[i]]) * coda_glmnet_Crohn$`log-contrast coefficients`[i]
  my.sum <-  my.sum + current
}
ratio_predictor_1 <- my.sum


current_df$ratio <- ratio_predictor_1

current_df[, c('ratio', 'FIT: number of relevant lesions')]
current_df[, c('ratio', 'Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)')]
#current_df$``

plot_df <- current_df[current_df$`Scopie 1: Advancedlaesie (0=CRC, 1= AA, 2= ASP, 3=NAA, 4=NASP, 5=geen lesies)` > 0,]

plot_df[, c('ratio', 'Scopie 1: Advancedlaesie (0=CRC, 1= AA, 2= ASP, 3=NAA, 4=NASP, 5=geen lesies)')]




#interesting_df <- current_df[current_df$ratio > 5,]
```



```{r codacore permutations}
current_df <- lynch_df[!is.na(lynch_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`),]
current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`[current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`==0] = 'No'
current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`[current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`==1] = 'Yes'

x <- current_df[,1:244]
y <- current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`




aucs <- c()
for (i in 1:100){
  

  
  trainIndex <- sample(1:nrow(x), 0.75 * nrow(x))
  xTrain <- x[trainIndex, ]
  yTrain <- y[trainIndex]
  
  
  model <- codacore(
    xTrain,
    yTrain,
    logRatioType = 'amalgamations', # can also use 'amalgamations'
    lambda = 1                 # regularization parameter (1 corresponds to "1SE rule")
  )
  
  
  xTest <- x[-trainIndex, ]
  yTest <- y[-trainIndex]
  #yHat <- predict(model, xTest, logits = F)
  #> Test set AUC = 0.80537
  # Convert probabilities into a binary
  # class
  #failure <- yHat < 0.5
  #success <- yHat >= 0.5
  #yHat[failure] <- 'IBD'
  #yHat[success] <- 'Control'

  
  yHat <- predict(model, xTest, logits = F,
      numLogRatios = 1)


  aucs <- c(aucs, pROC::auc(pROC::roc(yTest,
      yHat, quiet = T)))
}
cat("Test set mean AUC =", mean(aucs))
cat("Test set sd AUC =", sd(aucs))
```


## split lesies into severe or not
```{r }


current_df <- lynch_df[!is.na(lynch_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`),]
current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`[current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`==0] = 'No'
current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`[current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`==1] = 'Yes'

x <- current_df[,1:244]
y <- current_df$`Relevant lesion? = CRC, adenoma, adv serrated polyp (1=yes, 0=no)`


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`





```


## split lesies into severe or not
```{r }


current_df <- lynch_df[!is.na(lynch_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`),]

current_df <- current_df[as.integer(current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`) != -98,]
current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)` <- as.integer(current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`)
current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`[current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`==0] = 'No'
current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`[current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`==1] = 'Yes'
x <- current_df[,1:244]
y <- current_df$`CRC + Adv adenoma? (1=yes, 0=no, -98 = missing; non-adv adenoma en adv serrated polyp)`


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




```
### linear outcome level of severity, predict like 3+ and see how well that works

```{r }


current_df <- lynch_df
#lynch_df$`Type of lesion`
current_df <- current_df[as.numeric(current_df$`Scopie 1: Advancedlaesie (0=CRC, 1= AA, 2= ASP, 3=NAA, 4=NASP, 5=geen lesies)`) != -98,]

x <- current_df[,1:242]
y <- as.numeric(current_df$`Scopie 1: Advancedlaesie (0=CRC, 1= AA, 2= ASP, 3=NAA, 4=NASP, 5=geen lesies)`)


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`



```





### part 2 femkes analysis setup

```{r AllNeoplasia_controls }

target_var <- 'AllNeoplasia_controls'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`





#current_df <- current_df[as.integer(current_df[[target_var]]) != -98,]
#current_df[[target_var]] <- as.integer(current_df[[target_var]])
#current_df[[target_var]][current_df[[target_var]]==0] = 'No'
#current_df[[target_var]][current_df[[target_var]]==1] = 'Yes'

```



```{r AdvAdenomasCRC_controls}


target_var <- 'AdvAdenomasCRC_controls'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`


```

```{r AdvAdenomas_nonAdvAdenomas}


target_var <- 'AdvAdenomas_nonAdvAdenomas'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




```


```{r CRC_controls}
# too few samples


target_var <- 'CRC_controls'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




```


```{r LR_Neoplasia_controls}



target_var <- 'LR_Neoplasia_controls'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`



```



```{r HR_Neoplasia_control}




target_var <- 'HR_Neoplasia_controls'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`


```

```{r NoNeo_High_Lowrisk}


target_var <- 'NoNeo_High_Lowrisk'

current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]

x <- current_df[,1:282]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




```

```{r NoNeo_Mutation}

## split into 4 groups then compare between the groups

target_var <- 'NoNeo_Mutation'
current_df <- lynch_df[!is.na(lynch_df[[target_var]]),]


df_mlh1 <- current_df[current_df[[target_var]] == 'MLH1', ]
df_msh2 <- current_df[current_df[[target_var]] == 'MSH2/EPCAM', ]
df_msh6 <- current_df[current_df[[target_var]] == 'MSH6', ]
df_pms2 <- current_df[current_df[[target_var]] == 'PMS2', ]

df_mlh1_v_msh2 <- rbind(df_mlh1, df_msh2)
df_mlh1_v_msh6 <- rbind(df_mlh1, df_msh6)
df_mlh1_v_pms2 <- rbind(df_mlh1, df_pms2)
df_msh2_v_msh6 <- rbind(df_msh2, df_msh6)
df_msh2_v_pms2 <- rbind(df_msh2, df_pms2)
df_msh6_v_pms2 <- rbind(df_msh6, df_pms2)

#1

x <- df_mlh1_v_msh2[,1:244]
y <- df_mlh1_v_msh2[[target_var]]

coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




#2
x <- df_mlh1_v_msh6[,1:282]
y <- df_mlh1_v_msh6[[target_var]]

coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`


#3
x <- df_mlh1_v_pms2[,1:282]
y <- df_mlh1_v_pms2[[target_var]]

coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`


#4
x <- df_msh2_v_msh6[,1:282]
y <- df_msh2_v_msh6[[target_var]]

coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




#5
x <- df_msh2_v_pms2[,1:282]
y <- df_msh2_v_pms2[[target_var]]

coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`




#6
x <- df_msh6_v_pms2[,1:282]
y <- df_msh6_v_pms2[[target_var]]

coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 5)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`
```





```{r lynch v lifelines}

lynch_LL_metadata <- read.csv('/Users/iwan/Research/Lynch_predictions/Lynch_Lifelines/Lynch_LifeLines_meta_all.csv')

lynch_LL_species <- read.delim2('/Users/iwan/Research/Lynch_predictions/Lynch_Lifelines/Lynch_LifeLines_species_all_filt.csv', sep =',')


rownames(lynch_LL_species) <-  lynch_LL_species$X

lynch_LL_species$X <- NULL
#new_names <- c()
#for (i in colnames(lynch_species)){
#  new_names <- c(new_names, paste(str_split(i, '_')[[1]][1:3], collapse = '_'))
#}
#colnames(lynch_species) <- new_names



#lynch_species <- as.data.frame(t(lynch_species))


#filter

#saved_rownames <- rownames(lynch_species)
#lynch_species$X <- NULL

#lynch_species <- mutate_all(lynch_species, function(x) as.numeric(as.character(x)))


#Taxa_DR_species <- filterMetaGenomeDF(lynch_species, presPerc = 0.20,minMRelAb = 0.01 ,minMedRelAb=0.0,
 #                                     rescaleTaxa=T,verbose=T,
#                                      keepDomains=c('Bacteria','Archaea'),
 #                                     keepLevels=c('S'),
#                                      keepUnknown=F) 


#updated_rownames <- str_split_i(saved_rownames, '_', 1)
#row.names(Taxa_DR_species) <- saved_rownames
#Taxa_DR_species <- na.omit(Taxa_DR_species)

shortnames <- c()
for (i in colnames(lynch_LL_species)){
  shortnames <- c(shortnames, paste('s__' ,str_split_i(i, '__',8)))
}
#shortnames[1] <- 'X'
colnames(lynch_LL_species) <- shortnames

lynch_LL_species <- mutate_all(lynch_LL_species, function(x) as.numeric(as.character(x)))


lynch_LL_species[lynch_LL_species == 0] <- NA
lynch_LL_species[sapply(lynch_LL_species, is.numeric)] <- lapply(lynch_LL_species[sapply(lynch_LL_species, is.numeric)], function(a) ifelse(is.na(a), min(a, na.rm = TRUE)/2, a))

#rownames(lych_metadata) <- lych_metadata$X
#lych_metadata$X <- NULL

lynch_LL_df <- merge(lynch_LL_species, lynch_LL_metadata, by.x = 0, by.y = 'Participant_ID')
rownames(lynch_LL_df) <- lynch_LL_df$Row.names
lynch_LL_df$Row.names <- NULL

lynch_only <- lynch_LL_df[lynch_LL_df$cohort == 'Lynch',]

```


```{r }


current_df <- lynch_LL_df[!is.na(lynch_LL_df$cohort),]

x <- current_df[,1:286]
y <- current_df$cohort


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10, nvar=15)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`



```

```{r }


current_df <- lynch_only[!is.na(lynch_only$Neoplasia_Control),]

current_df$Neoplasia_Control[current_df$Neoplasia_Control==0] = 'No'
current_df$Neoplasia_Control[current_df$Neoplasia_Control==1] = 'Yes'

x <- current_df[,1:286]
y <- current_df$Neoplasia_Control


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10, nvar=15)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`



```



```{r HR_Neoplasia_control}




target_var <- 'HR_Neoplasia_controls'

current_df <- lynch_only[!is.na(lynch_only[[target_var]]),]
current_df$Neoplasia_Control[current_df$HR_Neoplasia_controls==0] = 'No'
current_df$Neoplasia_Control[current_df$HR_Neoplasia_controls==1] = 'Yes'

x <- current_df[,1:286]
y <- current_df[[target_var]]


coda_glmnet_Crohn<-coda_glmnet(x=x,y=y, nfolds = 10)
coda_glmnet_Crohn$`mean cv-AUC`
coda_glmnet_Crohn$`sd cv-AUC`


```

